### ISSUE TITLE
Format error when trying to add a picture

### ISSUE THREAD

**Issue by Oliver-Luo** [sils1297/guadec-presentation-templates#2]
I encountered a format problem in the first page when trying to add an image into this pdf.
Here are the snapshot of the md and the pdf files.

![1](https://cloud.githubusercontent.com/assets/11568355/8986318/37e6d12a-370e-11e5-90a3-906c8fd86c42.png)
![2](https://cloud.githubusercontent.com/assets/11568355/8986317/37e21a36-370e-11e5-96ad-359f83519bbd.png)

**Comment by sils** [comment]
@lonely-pluto thanks for reporting. I can reproduce that.

@Kekun I've generated tex files first for the faulty then for the other version, could you take a look at those?

They are here: https://gist.github.com/sils1297/e51cf8a4ab902d4e6819

**Comment by sils** [comment]
@Kekun Problem seems to be that pandoc sets some default properties for all graphics when using some so you may need to override those in your template.

**Comment by Kekun** [comment]
Actually, in both cases the title page's background is wrong when using 16/9 and pandoc, but in different ways. I'm investigating.
